app:
  mode: development
  ocr_language: eng
  ui_language: fr
database:
  path: ocr_receipts.db
  timeout: 30
file_naming:
  active_template: default
  date_format: '%Y-%m-%d'
  include_invoice_number: true
  template: '{project}_{documentType}_{date}_{company}_{total}'
  templates:
    default:
      active: true
      description: Standard template with project, date, company, and total
      name: Default Template
      template: '{project}_{documentType}_{date}__{category}_{company}_${total}'
    facture:
      active: false
      description: null
      name: facture
      template: '{project}_{documentType}_{date}_{company}_{category}_${total}'
    testtemplate:
      active: false
      description: null
      name: testtemplate
      template: '{project}'
gui:
  auto_save: true
  show_preview: true
  window_size:
  - 1400
  - 900
logging:
  file: app.log
  level: INFO
ocr:
  confidence_threshold: 0.8
  max_retries: 3
