app:
  mode: development
  ocr_language: eng
  ui_language: en
database:
  path: ocr_receipts.db
  timeout: 30
file_naming:
  active_template: default
  date_format: '%Y-%m-%d'
  include_invoice_number: true
  templates:
    default:
      active: true
      description: Standard template with project, date, company, and total
      name: Default Template
      template: '{project}_{documentType}_{date}_{company}_{total}'
gui:
  auto_save: true
  show_preview: false
  window_size:
  - 1200
  - 800
logging:
  file: app.log
  level: INFO
ocr:
  confidence_threshold: 0.75
  max_retries: 5
